<?php

namespace App\View\Components\include;

use Illuminate\Support\Facades\Blade;
use Illuminate\View\Component;
use Illuminate\View\View;

class EditTable extends Component
{
    public $columns;
    public $model;
    public $action;
    public function data()
    {
        return parent::data(); // TODO: Change the autogenerated stub
    }

    /**
     * Create a new component instance
     *
     * @param string $action имя ресурса
     * @param array $columns названия столбцов которые будут отображатся на frontend
     * @param array $model
     *
     * @return void
     */
    public function __construct(string $action, array $columns, array $model)
    {
        $this->action = $action;
        $this->columns = $columns;
        $this->model = $model;
    }

    /**
     * Get the view / contents that represent the component.
     *
     * @return view
     */
    public function render(): view
    {
        return view('components.include.edit-table');
    }

}
